version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@1.2.3

workflows:
  heroku_deploy:
    jobs:
      - node/test
      - heroku/deploy-via-git:
          requires:
            - node/test